// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlnjIOACLmOVeula7x9HdTkEz-PU6okR8',
    appId: '1:670823984510:web:5da144f4522b6c442dd72f',
    messagingSenderId: '670823984510',
    projectId: 'flutter-task-2-43f0c',
    authDomain: 'flutter-task-2-43f0c.firebaseapp.com',
    storageBucket: 'flutter-task-2-43f0c.firebasestorage.app',
    measurementId: 'G-DE7B2G2SMK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC40HruKbkF0hTPDjNSp0e6GHTiXZuUszQ',
    appId: '1:670823984510:android:2f1d1332e59fcd692dd72f',
    messagingSenderId: '670823984510',
    projectId: 'flutter-task-2-43f0c',
    storageBucket: 'flutter-task-2-43f0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8wkSDbbqVfW0lN_2_tDNFXkhNojbhCdk',
    appId: '1:670823984510:ios:f08c56838ddee2182dd72f',
    messagingSenderId: '670823984510',
    projectId: 'flutter-task-2-43f0c',
    storageBucket: 'flutter-task-2-43f0c.firebasestorage.app',
    iosBundleId: 'com.example.flutterTask',
  );
}
